### ISSUE TITLE
Fails to initialize when opening .hs file

### ISSUE THREAD

**Issue by mikemcgowan** [dramforever/vscode-ghc-simple#16]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.10
- Version of VSCode: 1.29.1
- Version of Haskell-related tools:
    - Stack: 1.7.1 (it's also a problem with Stack 1.9.1)

VSCode `Help -> About` info:

```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

## Steps to reproduce

Open any `.hs` file

Expect extension features to be available. Instead, no features are available.

I see errors in the VSCode console (which don't happen when opening files that aren't `.hs`, and which don't happen when the extension is disabled):

![selection_023](https://user-images.githubusercontent.com/2492670/48895890-186d4f00-ee3e-11e8-974f-2ffd7e4631d7.png)

## Workspace

n/a

**Comment by dramforever** [comment]
Try opening the bottom panel with 'problems' 'output' etc and go to the 'output' tab and go to 'GHC' from the dropdown on the right. Paste any output you see there. (If you don't see 'GHC' tell me that as well.)

Also, does `stack exec ghci` work for you in the VSCode terminal?

**Comment by mikemcgowan** [comment]
So, immediately after downloading the "Parallel Letter Frequency" problem from [exercism.io](https://exercism.io/) which gives me these files:

```
 + 10:46:29 ~/exercism/haskell/parallel-letter-frequency$ tree -a
.
├── bench
│   └── Benchmark.hs
├── .exercism
│   └── metadata.json
├── package.yaml
├── README.md
├── src
│   └── Frequency.hs
├── stack.yaml
└── test
    └── Tests.hs

4 directories, 7 files
```
I then open VSCode in the same directory with `code .`, then open `Frequency.hs`, and I see in the GHC output the following:

```
    -> :set prompt ""
ghci | parallel-letter-frequency-0.1.0.3: configure (lib)
ghci | Configuring parallel-letter-frequency-0.1.0.3...
ghci | parallel-letter-frequency-0.1.0.3: initial-build-steps (lib)
ghci | The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O2
ghci | Configuring GHCi with the following packages: parallel-letter-frequency
ghci | 
ghci | Warning: Didn't find expected autogen file:
ghci |          /home/mike/exercism/haskell/parallel-letter-frequency/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/bench/autogen/cabal_macros.h
ghci | GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
ghci | <command line>: cannot satisfy -package criterion-1.4.1.0
ghci |     (use -v for more information)
```

At this point, the extension's features aren't available, e.g. clicking on things in `Frequency.hs` doesn't show the type annotation at the end of the line.

Both `stack exec ghci` and `stack ghci` (I normally use the latter) both work in the VSCode terminal.

Now that I know where to find GHC output (thanks!) I can see my issue is specific to this particular project; I couldn't reproduce the problem opening a `foo.hs` file that contained only `main = putStrLn "Hello, world"` in an otherwise empty directory.

(I don't know why it's telling me it can't satisfy `criterion-1.4.1.0` because I'm using LTS Haskell [12.5](https://www.stackage.org/lts-12.5) and that's the exact version of `criterion` it has.)

**Comment by mikemcgowan** [comment]
So, I got rid of the problem by commenting out both `tests` and `benchmarks` in `package.yaml`, deleting the generated `parallel-letter-frequency.cabal` file, deleting the `.stack-work` directory, closing the VSCode folder, closing VSCode itself. Then restarting everything.

```
name: parallel-letter-frequency
version: 0.1.0.3

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Frequency
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

# tests:
#   test:
#     main: Tests.hs
#     source-dirs: test
#     dependencies:
#       - parallel-letter-frequency
#       - hspec

# benchmarks:
#   bench:
#     ghc-options: -threaded -with-rtsopts=-N -O2

#     main: Benchmark.hs
#     source-dirs: bench
#     dependencies:
#       - parallel-letter-frequency
#       - criterion
```

This was a problem with a specific project and not with the extension itself. Sorry to have wasted your time, and thanks for the useful info about where to find GHC output.
